version = 1

[[migrations]]
id = 9124886579048122415
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 8101756793848107859
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 4537668072844659691
name = "0002_migration.sql"
snapshot_name = "0002_snapshot.toml"
